devices:
  - name: Switch1
    id: xxxxxxxxxxxxxxxxxxx
    key: yyyyyyyyyyyyyyyyy
    ip: 'xxx.xxx.xxx.xxx'
    version: '3.3'
    steps:
      - days: 0-6 # wwek days 0 - Monday : 6 - Sunday
        start: 00 # start at 00:00
        end: 24 # end at 24:00
        count: 3 # switched on for 3 hours in the period
        timezone: CET

cache-config:
  type: redis
  prefix: smap-cp-

database-config:
  type: sqlite
  spec:
    file: database.db

application-config:
  timer: 10
  timezone: UTC