name: Latest build

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        env:
          USER: ${{ secrets.DOCKERHUB_USERNAME }}
          PASS: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker login -u $USER -p $PASS
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: eryalus/smap-cp:latest